### ISSUE TITLE
Example in README not working

### ISSUE THREAD

**Issue by jmilldotdev** [SamLewis0602/obsidian-custom-js#1]
Hello,

I have tried to follow the example in the README and it is not working.

I have file scripts/coolString.js with the following:

```javascript
class CoolString {
  coolify(s) {
      return `😎 ${s} 😎`
  }
}
```

and I have the following Dataviewjs block in test.md

```dataviewjs
const {CoolString} = customJS
dv.list(dv.pages().file.name.map(n => CoolString.coolify(n)))
```

When I switch to preview mode I get the following:

Evaluation Error: TypeError: Cannot read property 'coolify' of undefined
    at eval (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1215379)), <anonymous>:2:50)
    at Array.map (<anonymous>)
    at Proxy.map (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:9080:39)
    at eval (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1215379)), <anonymous>:2:30)
    at DataviewInlineApi.eval (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:12386:16)
    at evalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:12387:7)
    at DataviewJSRenderer.eval (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:12877:17)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:26:71)
    at new Promise (<anonymous>)

**Comment by jmilldotdev** [comment]
It seems like this is resolved by adding this file explicitly in the 'files to load' field in the plugin settings, which is not mentioned in the documentation afaik. Also, the app must be quit and reloaded to take effect.

**Comment by jmilldotdev** [comment]
Did not see the bit about adding it in the settings tab 😅

**Comment by SamLewis0602** [comment]
No problem! I'll find a way to clear it up in the README.
