### ISSUE TITLE
I am unable to get the "advanced example" of your daily notes to work

### ISSUE THREAD

**Issue by Peggy-Ann** [SamLewis0602/obsidian-custom-js#23]
I reaaly like this plugin I have so many ideas to try out but I cant get it to work... :-(
I have managed to get the coolScript to load but the "Today tasks" will not work(it looks really great in the readme btw!).

I have the following script in my notes:

>```dataviewjs
>const {DvTasks} = customJS
>DvTasks.getOverdueTasks({app, dv, luxon, that:this, date:'2021-08-25'})
>```
>
>```dataviewjs
>const {DvTasks} = customJS
>DvTasks.getTasksNoDueDate({app, dv, luxon, that:this})
>```
>
>### Today's Tasks
>```dataviewjs
>const {DvTasks} = customJS
>DvTasks.getTodayTasks({app, dv, luxon, that:this, date:'2021-08-25'}) 
>```
>### Daily Journal

in my scriptfolder (in the valve root) I have dvTasks.js and coolString.js.
My setting in CustomJS  is folderpath: scripts

The error I get is the following

>Evaluation Error: TypeError: Cannot read property 'api' of undefined
    at DvTasks.getTasksTable (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1)), <anonymous>:65:33)
    at DvTasks.getOverdueTasks (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1)), <anonymous>:36:17)
    at eval (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1362602)), <anonymous>:2:9)
    at DataviewInlineApi.eval (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:15671:16)
    at evalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:15672:7)
    at asyncEvalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:15682:32)
    at DataviewJSRenderer.render (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:16267:19)
    at DataviewJSRenderer.onload (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:16001:14)
    at DataviewJSRenderer.t.load (app://obsidian.md/app.js:1:630512)
    at e.t.addChild (app://obsidian.md/app.js:1:630936)
Evaluation Error: TypeError: Cannot read property 'api' of undefined
    at DvTasks.getTasksTable (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1)), <anonymous>:65:33)
    at DvTasks.getTasksNoDueDate (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1)), <anonymous>:44:17)
    at eval (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1362602)), <anonymous>:2:9)
    at DataviewInlineApi.eval (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:15671:16)
    at evalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:15672:7)
    at asyncEvalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:15682:32)
    at DataviewJSRenderer.render (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:16267:19)
    at DataviewJSRenderer.onload (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:16001:14)
    at DataviewJSRenderer.t.load (app://obsidian.md/app.js:1:630512)
    at e.t.addChild (app://obsidian.md/app.js:1:630936)
Today's Tasks
Evaluation Error: TypeError: Cannot read property 'api' of undefined
    at DvTasks.getTasksTable (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1)), <anonymous>:65:33)
    at DvTasks.getTodayTasks (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1)), <anonymous>:27:17)
    at eval (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1362602)), <anonymous>:2:9)
    at DataviewInlineApi.eval (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:15671:16)
    at evalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:15672:7)
    at asyncEvalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:15682:32)
    at DataviewJSRenderer.render (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:16267:19)
    at DataviewJSRenderer.onload (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:16001:14)
    at DataviewJSRenderer.t.load (app://obsidian.md/app.js:1:630512)
    at e.t.addChild (app://obsidian.md/app.js:1:630936)
Daily Journal
---
What am I doing wrong? I am really at a loss here, thankful for any insights.

**Comment by SamLewis0602** [comment]
I'm pretty sure this is caused by line 65 in the example code:
```
const { update } = metaedit.api
```

That would fail if you don't have the metaedit plugin installed, hence the error `Evaluation Error: TypeError: Cannot read property 'api' of undefined`. It's trying to read `metaedit.api`, but metaedit is undefined. If you want it to just work, you can install metaedit. However, this was simply meant to be an example to inspire. To get it to work you'd need to install the buttons plugin as well. It may be better to start from scratch and slowly build out your own version, using the example as a reference.

**Comment by SamLewis0602** [comment]
Feel free to reopen if it still fails after trying the above suggestions.

**Comment by Peggy-Ann** [comment]
Well, you did inspire! :-)
I'll try and see if I can get it to work. Thanks for taking the time to look into it!

**Comment by SamLewis0602** [comment]
No worries, good luck 😁
