### ISSUE TITLE
having trouble with the advanced example

### ISSUE THREAD

**Issue by swuphoto** [SamLewis0602/obsidian-custom-js#24]
Hi,

I got the first example to work, however can't get the advanced example to work.  The error is at the bottom of this message.
Do I need any special notes for this example to work?  thanks!

Evaluation Error: TypeError: Cannot destructure property 'createButton' of 'buttons' as it is undefined.
    at DvTasks.getTasksTable (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1362602)), <anonymous>:67:13)
    at DvTasks.getTodayTasks (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1362602)), <anonymous>:27:17)
    at eval (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1362602)), <anonymous>:2:9)
    at DataviewInlineApi.eval (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:15671:16)
    at evalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:15672:7)
    at asyncEvalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:15682:32)
    at DataviewJSRenderer.render (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:16267:19)
    at DataviewJSRenderer.onload (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:16001:14)
    at DataviewJSRenderer.t.load (app://obsidian.md/app.js:1:630512)
    at e.t.addChild (app://obsidian.md/app.js:1:630936)
    at Object.addChild (app://obsidian.md/app.js:1:1429122)
    at DataviewPlugin.dataviewjs (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:15780:19)
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:15714:105)
    at app://obsidian.md/app.js:1:756294
    at Function.e.postProcess (app://obsidian.md/app.js:1:1430182)
    at e.postProcess (app://obsidian.md/app.js:1:1428997)
    at h (app://obsidian.md/app.js:1:744502)
    at t.onRender (app://obsidian.md/app.js:1:744762)
    at e (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:333:36332)

**Comment by SamLewis0602** [comment]
See #23 . It's the same issue but with the buttons plugin instead of metaedit. The example is not meant to work out of the box, use it as inspiration/reference to write your own setup.
