### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by antoniocanas** [SamLewis0602/obsidian-custom-js#6]
Hi, I can't make it to work: I've set the `scripts` directory on the settings, created it on my vault with the `coolString.js` file containing the class and put the dataviewjs example from the readme in a daily note.

What could be happening? No error in the console, just this one on the preview:
```
Evaluation Error: TypeError: Cannot read property 'coolify' of undefined
    at eval (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1215379)), <anonymous>:2:50)
    at Array.map (<anonymous>)
    at Proxy.map (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:9037:39)
    at eval (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1215379)), <anonymous>:2:30)
    at DataviewInlineApi.eval (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:12520:16)
    at evalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:12521:7)
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:12532:36)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:26:71)
    at new Promise (<anonymous>)
```

**Comment by SamLewis0602** [comment]
Hey! Something must be set up incorrectly. Can you post exactly what you put in your coolString.js file?

**Comment by antoniocanas** [comment]
My bad. I was setting the directory inside the `.obsidian` one, like the default `snippets`. Thanks for answering and for creating this cool plugin!

**Comment by SamLewis0602** [comment]
No problem! Enjoy!
